# Generated by Django 4.2.3 on 2023-07-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('hours', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('wait_time', models.IntegerField()),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('favorited', models.BooleanField(default=False)),
            ],
        ),
    ]
