# Generated by Django 4.2.3 on 2023-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeteatz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='down_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='up_rating',
            field=models.IntegerField(default=0),
        ),
    ]
