# Generated by Django 4.2.3 on 2023-07-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeteatz', '0002_vendor_down_rating_vendor_up_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='distanceFromUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
