# Generated by Django 4.2.3 on 2023-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeteatz', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
